//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace @__Subject_Loading_and_Room_Assignment_Monitoring_System.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=pogitayo;Initial Catalog=Schooldb;Integrated Security=True;Connect Ti" +
            "meout=30;Encrypt=True;TrustServerCertificate=True")]
        public string SchooldbConnectionString {
            get {
                return ((string)(this["SchooldbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=pogitayo;Initial Catalog=Schooldb;Integrated Security=True;Connect Ti" +
            "meout=30;Encrypt=False;TrustServerCertificate=True")]
        public string SchooldbConnectionString1 {
            get {
                return ((string)(this["SchooldbConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=pogitayo;Initial Catalog=Schooldb;Integrated Security=True;Connect Ti" +
            "meout=30;Encrypt=True;TrustServerCertificate=True")]
        public string SchooldbConnectionString2 {
            get {
                return ((string)(this["SchooldbConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=pogitayo;Initial Catalog=Schooldb;Integrated Security=True;Connect Ti" +
            "meout=30;Encrypt=True;TrustServerCertificate=True")]
        public string SchooldbConnectionString3 {
            get {
                return ((string)(this["SchooldbConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=pogitayo;Initial Catalog=Schooldb;Integrated Security=True;Connect Ti" +
            "meout=30;Encrypt=True;TrustServerCertificate=True")]
        public string SchooldbConnectionString4 {
            get {
                return ((string)(this["SchooldbConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=pogitayo;Initial Catalog=Schooldb;Integrated Security=True;Connect Ti" +
            "meout=30;Encrypt=True;TrustServerCertificate=True")]
        public string SchooldbConnectionString5 {
            get {
                return ((string)(this["SchooldbConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=pogitayo;Initial Catalog=Schooldb;Integrated Security=True;Connect Ti" +
            "meout=30;Encrypt=True;TrustServerCertificate=True")]
        public string SchooldbConnectionString6 {
            get {
                return ((string)(this["SchooldbConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=pogitayo;Initial Catalog=Schooldb;Integrated Security=True;Connect Ti" +
            "meout=30;Encrypt=True;TrustServerCertificate=True")]
        public string SchooldbConnectionString7 {
            get {
                return ((string)(this["SchooldbConnectionString7"]));
            }
        }
    }
}
